from pathlib import Path
import json
import re

BASE = Path("/Volumes/AI_DRIVE/TitanAgent")
PRODUCTS = BASE / "products"
PRODUCTS.mkdir(parents=True, exist_ok=True)


def slug(value):
    value = str(value or "").strip().lower()
    value = re.sub(r"[^a-z0-9._-]+", "-", value)
    return value.strip("-") or "product"


def title_case(value):
    return slug(value).replace("-", " ").replace("_", " ").title()


def clean_description(value, name):
    value = str(value or "").strip()
    return value or f"{title_case(name)} generated by Titan."


def product_root(name):
    root = (PRODUCTS / slug(name)).resolve()
    if not str(root).startswith(str(PRODUCTS.resolve())):
        raise ValueError("Invalid product path.")
    return root


def template_names():
    return [
        "python_cli",
        "flask_app",
        "static_website",
        "api_service",
        "flask_dashboard",
        "landing_page",
    ]


def list_templates():
    return {
        "templates": [
            {"name": "python_cli", "description": "Simple Python command-line app."},
            {"name": "flask_app", "description": "Small Flask app with home and health route."},
            {"name": "static_website", "description": "Static HTML/CSS/JS website."},
            {"name": "api_service", "description": "Flask JSON API service."},
            {"name": "flask_dashboard", "description": "Flask dashboard with chat-style UI."},
            {"name": "landing_page", "description": "Modern product landing page."},
        ]
    }


def fill(text, name, description):
    return (
        text
        .replace("__NAME__", slug(name))
        .replace("__TITLE__", title_case(name))
        .replace("__DESC__", clean_description(description, name))
    )


def write_files(root, files):
    root.mkdir(parents=True, exist_ok=True)
    for rel, body in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")


def python_cli_files(name, description):
    return {
        "main.py": fill('''#!/usr/bin/env python3
import argparse
import json


def main():
    parser = argparse.ArgumentParser(description="__DESC__")
    parser.add_argument("--message", default="__TITLE__ online")
    args = parser.parse_args()
    print(json.dumps({"product": "__NAME__", "message": args.message, "status": "ok"}, indent=2))


if __name__ == "__main__":
    main()
''', name, description),
        "requirements.txt": "",
        "README.md": fill('''# __TITLE__

__DESC__

Run:

python3 main.py --message hello
''', name, description),
    }


def flask_app_files(name, description):
    return {
        "app.py": fill('''import os
from flask import Flask, jsonify, render_template_string

app = Flask(__name__)

HTML = """
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>__TITLE__</title>
  <style>
    body { margin:0; min-height:100vh; display:grid; place-items:center; background:#111214; color:white; font-family:system-ui; }
    main { width:min(760px, calc(100vw - 40px)); padding:34px; border-radius:28px; background:rgba(255,255,255,.06); border:1px solid rgba(255,255,255,.1); }
    h1 { font-size:56px; letter-spacing:-.06em; margin:0; }
    p { color:#a1a1aa; }
  </style>
</head>
<body>
  <main>
    <h1>__TITLE__</h1>
    <p>__DESC__</p>
    <p>Health: /health</p>
  </main>
</body>
</html>
"""

@app.route("/")
def home():
    return render_template_string(HTML)

@app.route("/health")
def health():
    return jsonify({"status": "ok", "product": "__NAME__"})

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=int(os.environ.get("PORT", 5055)), debug=True)
''', name, description),
        "requirements.txt": "flask\n",
        "README.md": fill('''# __TITLE__

__DESC__

Run:

pip install -r requirements.txt
python3 app.py
''', name, description),
    }


def static_website_files(name, description):
    return {
        "index.html": fill('''<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>__TITLE__</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <main>
    <section class="hero">
      <div class="badge">Built by Titan</div>
      <h1>__TITLE__</h1>
      <p>__DESC__</p>
      <button onclick="demo()">Launch demo</button>
    </section>
  </main>
  <script src="app.js"></script>
</body>
</html>
''', name, description),
        "style.css": '''body {
  margin: 0;
  min-height: 100vh;
  background: radial-gradient(circle at 50% -20%, rgba(232,171,67,.24), transparent 34%), linear-gradient(180deg, #111214, #18191c);
  color: white;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
}
main { min-height: 100vh; display: grid; place-items: center; padding: 28px; }
.hero {
  width: min(900px, 100%);
  border: 1px solid rgba(255,255,255,.1);
  background: rgba(255,255,255,.055);
  border-radius: 30px;
  padding: 42px;
  box-shadow: 0 24px 80px rgba(0,0,0,.34);
}
.badge {
  display: inline-flex;
  padding: 8px 12px;
  border-radius: 999px;
  background: rgba(232,171,67,.16);
  border: 1px solid rgba(232,171,67,.22);
  color: #ffd08e;
  font-weight: 800;
}
h1 { margin: 18px 0 10px; font-size: clamp(46px, 8vw, 92px); letter-spacing: -.07em; }
p { color: #a1a1aa; font-size: 18px; line-height: 1.55; max-width: 680px; }
button { margin-top: 18px; border: 0; border-radius: 999px; padding: 14px 18px; background: #e8ab43; color: #111214; font-weight: 850; cursor: pointer; }
''',
        "app.js": 'function demo() { alert("Titan product demo online."); }\n',
        "README.md": fill('''# __TITLE__

__DESC__

Run:

python3 -m http.server 5060
''', name, description),
    }


def api_service_files(name, description):
    return {
        "app.py": fill('''import os
from datetime import datetime
from flask import Flask, jsonify, request

app = Flask(__name__)
ITEMS = []

@app.route("/")
def home():
    return jsonify({"service": "__NAME__", "title": "__TITLE__", "description": "__DESC__", "endpoints": ["/health", "/api/items"]})

@app.route("/health")
def health():
    return jsonify({"status": "ok", "time": datetime.now().isoformat(timespec="seconds")})

@app.route("/api/items", methods=["GET", "POST"])
def items():
    if request.method == "POST":
        data = request.json or {}
        item = {"id": len(ITEMS) + 1, "name": data.get("name", "Untitled"), "created_at": datetime.now().isoformat(timespec="seconds")}
        ITEMS.append(item)
        return jsonify(item), 201
    return jsonify({"items": ITEMS})

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=int(os.environ.get("PORT", 5055)), debug=True)
''', name, description),
        "requirements.txt": "flask\n",
        "README.md": fill('''# __TITLE__

__DESC__

Run:

pip install -r requirements.txt
python3 app.py

Test:

curl http://127.0.0.1:5055/health
''', name, description),
    }


def flask_dashboard_files(name, description):
    return {
        "app.py": fill('''import os
from flask import Flask, jsonify, render_template_string, request

app = Flask(__name__)
MESSAGES = []

HTML = """
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>__TITLE__</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { margin:0; min-height:100vh; background:#111214; color:white; font-family:system-ui; }
    main { width:min(980px, calc(100vw - 36px)); margin:42px auto; }
    h1 { font-size:64px; letter-spacing:-.07em; margin:0 0 14px; }
    .panel { border:1px solid rgba(255,255,255,.1); background:rgba(255,255,255,.055); border-radius:28px; overflow:hidden; }
    .messages { min-height:420px; max-height:520px; overflow-y:auto; padding:18px; display:grid; gap:12px; }
    .bubble { border:1px solid rgba(255,255,255,.1); background:rgba(255,255,255,.06); border-radius:18px; padding:12px 14px; }
    form { display:flex; gap:10px; padding:14px; border-top:1px solid rgba(255,255,255,.1); }
    input { flex:1; border:0; outline:0; border-radius:999px; padding:0 16px; background:rgba(255,255,255,.08); color:white; font-size:16px; }
    button { border:0; border-radius:999px; padding:13px 18px; background:#e8ab43; color:#111214; font-weight:850; cursor:pointer; }
  </style>
</head>
<body>
  <main>
    <h1>__TITLE__</h1>
    <p>__DESC__</p>
    <section class="panel">
      <div class="messages" id="messages"></div>
      <form onsubmit="send(event)">
        <input id="input" placeholder="Send a message...">
        <button>Send</button>
      </form>
    </section>
  </main>
<script>
async function refresh() {
  const res = await fetch("/api/messages");
  const data = await res.json();
  const box = document.getElementById("messages");
  box.innerHTML = "";
  data.messages.forEach(m => {
    const d = document.createElement("div");
    d.className = "bubble";
    d.textContent = m;
    box.appendChild(d);
  });
  box.scrollTop = box.scrollHeight;
}
async function send(e) {
  e.preventDefault();
  const input = document.getElementById("input");
  const message = input.value.trim();
  if (!message) return;
  input.value = "";
  await fetch("/api/messages", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({message})});
  refresh();
}
refresh();
</script>
</body>
</html>
"""

@app.route("/")
def home():
    return render_template_string(HTML)

@app.route("/api/messages", methods=["GET", "POST"])
def messages():
    if request.method == "POST":
        MESSAGES.append((request.json or {}).get("message", ""))
    return jsonify({"messages": MESSAGES})

@app.route("/health")
def health():
    return jsonify({"status": "ok"})

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=int(os.environ.get("PORT", 5055)), debug=True)
''', name, description),
        "requirements.txt": "flask\n",
        "README.md": fill('''# __TITLE__

__DESC__

Run:

pip install -r requirements.txt
python3 app.py
''', name, description),
    }


def landing_page_files(name, description):
    files = static_website_files(name, description)
    files["index.html"] = fill('''<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>__TITLE__</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <nav><strong>__TITLE__</strong><a href="#features">Features</a><a href="#cta">Start</a></nav>
  <main>
    <section class="hero">
      <div class="badge">New Titan Product</div>
      <h1>Build faster with __TITLE__</h1>
      <p>__DESC__</p>
      <button onclick="demo()">Get started</button>
    </section>
    <section id="features" class="features">
      <article><h3>Fast</h3><p>Launch the first version quickly.</p></article>
      <article><h3>Clean</h3><p>Simple structure, readable files.</p></article>
      <article><h3>Expandable</h3><p>Ready for APIs, dashboards, and agents.</p></article>
    </section>
  </main>
  <script src="app.js"></script>
</body>
</html>
''', name, description)
    files["style.css"] += '''
nav { position: sticky; top: 0; display: flex; gap: 18px; align-items: center; padding: 18px 28px; background: rgba(17,18,20,.72); backdrop-filter: blur(14px); border-bottom: 1px solid rgba(255,255,255,.08); }
nav strong { margin-right: auto; }
nav a { color: #a1a1aa; text-decoration: none; }
.features { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; padding-bottom: 48px; }
article { border: 1px solid rgba(255,255,255,.1); background: rgba(255,255,255,.055); border-radius: 24px; padding: 20px; }
@media(max-width: 800px) { .features { grid-template-columns: 1fr; } }
'''
    return files


BUILDERS = {
    "python_cli": python_cli_files,
    "flask_app": flask_app_files,
    "static_website": static_website_files,
    "api_service": api_service_files,
    "flask_dashboard": flask_dashboard_files,
    "landing_page": landing_page_files,
}


def build_product(name, template="python_cli", description=""):
    name = slug(name)
    template = slug(template)
    description = clean_description(description, name)

    if template not in BUILDERS:
        return {"error": "Unknown product template.", "template": template, "available": template_names()}

    root = product_root(name)
    files = BUILDERS[template](name, description)
    write_files(root, files)

    meta = {"name": name, "template": template, "description": description, "files": sorted(files.keys())}
    (root / "product.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    return {"result": "product built", "name": name, "template": template, "path": str(root), "files": sorted(files.keys())}
